// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_format from "rescript/lib/es6/caml_format.js";

var percentages = [
  110,
  105,
  100,
  95,
  90,
  85,
  80,
  75,
  70,
  65,
  60,
  55,
  50
];

var categoryInfo = "\nPURE SPEED (over 110%)\nSPECIFIC SPEED (110 - 90%)\nSPECIAL SPEED (90 - 80%)\nBASIC SPEED (80 - 65%)\nGENERAL SPEED (65 - 50%)\nREGENERATION (under 50%)\n";

function computeSpeedTable(time400m) {
  var match = time400m.split(":");
  if (match.length !== 2) {
    return ;
  }
  var minutes = match[0];
  var seconds = match[1];
  var totalSeconds = (Math.imul(Caml_format.caml_int_of_string(minutes), 60) + Caml_format.caml_int_of_string(seconds) | 0) / 4;
  var onePercent = totalSeconds * 0.01;
  console.log("Your 400m time: " + time400m + "\n\nTraining speeds:\n----------------");
  Belt_Array.forEach(Belt_Array.map(percentages, (function (percentage) {
              return {
                      percentage: percentage,
                      speedPer100m: percentage >= 100 ? totalSeconds - (percentage - 100 | 0) * onePercent : totalSeconds + (100 - percentage | 0) * onePercent
                    };
            })), (function (paceInfo) {
          var padding = paceInfo.percentage < 100 ? " " : "";
          var percentage = String(paceInfo.percentage);
          var minutes = String((paceInfo.speedPer100m | 0) / 60 | 0);
          var n = String(Math.floor(paceInfo.speedPer100m % 60));
          var seconds = n.length < 2 ? "0" + n : n;
          console.log(padding + percentage + "%: " + minutes + "'" + seconds + "\"");
          
        }));
  console.log(categoryInfo);
  
}

if (process.argv.length >= 3) {
  computeSpeedTable(process.argv[2]);
}

export {
  percentages ,
  categoryInfo ,
  computeSpeedTable ,
  
}
/*  Not a pure module */
